language: python
python: 2.7
before_install:
  - virtualenv .testenv --no-download
  - .testenv/bin/pip install -r requirements.txt
  - .testenv/bin/nosetests -v --with-doctest
#  - make check
script:
  - source .testenv/bin/activate
  - sh .check_poc.sh
  - sh .check_exp.sh
  - rm -rf .testenv
notifications:
  email:
    recipients:
      - co0ontty@aliyun.com
    on_success: never # default: change
    on_failure: always # default: always
deploy:
  provider: releases
  api_key:
    secure: VTUH1acj4Yp_o5jwOXK3Lg
  file: build/sources.zip
  skip_cleanup: true
  on:
    tags: true