language: python
python: 2.7
before_install:
  - virtualenv .testenv --no-download
  - .testenv/bin/pip install -r requirements.txt
  - .testenv/bin/nosetests -v --with-doctest
#  - make check
script:
  - source .testenv/bin/activate
  - pocsuite -r pocs/ -u 127.0.0.1
  - rm -rf .testenv
notifications:
  email:
    recipients:
      - co0ontty@aliyun.com
    on_success: never # default: change
    on_failure: always # default: always
