language: python
python: 2.7
before_install:
  - make check
script:
  - echo "success"
notifications:
  email:
    recipients:
      - co0ontty@aliyun.com
    on_success: never # default: change
    on_failure: always # default: always
