language: python
python: 2.7
before_install:
#  - make check
script:
  - virtualenv .testenv --no-download
  - .testenv/bin/pip install -r requirements.txt
  - .testenv/bin/nosetests -v --with-doctest
  - rm -rf .testenv
notifications:
  email:
    recipients:
      - co0ontty@aliyun.com
    on_success: never # default: change
    on_failure: always # default: always
