language: python
python: 2.7
before_install:
  - virtualenv .testenv --no-download
  - .testenv/bin/pip install -r requirements.txt
  - rm -rf .testenv
script:
  - pocuite -r pocs/ -u 127.0.0.1
notifications:
  email:
    recipients:
      - co0ontty@aliyun.com
    on_success: never # default: change
    on_failure: always # default: always
