name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 2.7
      uses: actions/setup-python@v1
      with:
        python-version: 2.7
    - name: Install requirement
      run: |
        python -m pip install --upgrade pip
        pip install virtualenv
        virtualenv .testenv --no-download
        .testenv/bin/pip install -r requirements.txt
        .testenv/bin/nosetests -v --with-doctest
    - name: Test poc
      run: |
        source .testenv/bin/activate
        sh .check_poc.sh
        sh .check_exp.sh
        rm -rf .testenv
